project_id = "cjgjnudtelfdcubedxjo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
SMTP_PORT = 54325
POP3_PORT = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
s3_access_key_id = "625729a08b95bf1b7ff351a663f3a23c"
s3_secret_access_key = "850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6ded925b5250dc0"
s3_region = "local"
s3_bucket = "stub"

[auth]
enabled = true
port = 54324
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.ai-chat]
verify_jwt = true