// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjgjnudtelfdcubedxjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqZ2pudWR0ZWxmZGN1YmVkeGpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDUwNjMsImV4cCI6MjA3NDM4MTA2M30.GGls1dhvHdMMhkRKzcJl6T1WZPGkR3ZZT3KMKVUTpvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});